config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users
  resources :blogs, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end
  
  root 'top#index'
 end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
     if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
validates :title, presence: true

 belongs_to :user
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name,:email,:content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
# before_actionで下で定義したメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name)

  protected

    #deviseのストロングパラメーターにカラム追加するメソッドを定義
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
   before_action :set_blog, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @blogs = Blog.all
  
  end

  def new
     if params[:back]
      @blog = Blog.new(blogs_params)
    else
      @blog = Blog.new
    end

    end

  def create
     @blog = Blog.create(blogs_params)
     @blog.user_id = current_user.id
     if @blog.save
     redirect_to blogs_path,notice:"ブログを作成しました！"
     NoticeMailer.sendmail_blog(@blog).deliver
   else
     render action: 'new'
   end
 end

  def edit

  end

  def update

    @blog.update(blogs_params)
    redirect_to blogs_path,notice:"ブログを更新しました！"

  end

  def destroy

    @blog.destroy
    redirect_to blogs_path,notice:"ブログを削除しました！"
  end

  def confirm
    @blog = Blog.new(blogs_params)

    render :new if @blog.invalid?

 end

  private
    def blogs_params
      params.require(:blog).permit(:title, :content)
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    if params[:back]
      @contact = Contact.new(contacts_params)
    else
      @contact= Contact.new
    end


  end

  def create
     @contact = Contact.create(contacts_params)

    if @contact.save

     redirect_to root_path,notice:"お問い合わせありがとうございました！"

     NoticeMailer.sendmail_contact(@contact).deliver
   else
     render action: 'new'
   end
  end

  def confirm
      @contact =Contact.new(contacts_params)
      render :new if @contact.invalid?
  end
  private
    def contacts_params
      params.require(:contact).permit(:name,:email, :content)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end


module ActionView
  module Helpers
    module FormHelper
      def error_messages!(object_name, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if !resource || resource.errors.empty?

        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

        html = <<-HTML
          <div class="alert alert-danger">
            <ul>#{messages}</ul>
          </div>
        HTML

        html.html_safe
      end

      def error_css(object_name, method, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if resource.errors.empty?

        resource.errors.include?(method) ? 'has-error' : ''
      end
    end

    class FormBuilder
      def error_messages!(options = {})
        @template.error_messages!(@object_name, options.merge(object: @object))
      end

      def error_css(method, options = {})
        @template.error_css(@object_name, method, options.merge(object: @object))
      end
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
     def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog,url: choose_new_or_edit) do |f| %>
<%= f.error_messages! %>

  <%= f.label :タイトル %>
  <%= f.text_field :title,class: 'form-control'  %>
  <br>
  <%= f.label :内容 %>
  <%= f.text_field :content,class: 'form-control'  %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>


<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@blog) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <p>タイトル:<%= @blog.title %></p>
      <p>本文:<%= @blog.content %></p>
      <%= f.submit "登録",class: 'btn btn-primary btn-block'%>
    <% end %>
    <%= form_for(@blog, url: new_blog_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block'%>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを作成する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>ブログ一覧</h1>
      <%= link_to "ブログを作成する", new_blog_path, class: 'btn btn-default' %>
    <% @blogs.each do |blog| %>
    <div class="row">
      
    <p><%= blog.user.name %></p>
      <h4><strong><%= blog.title %></strong></h4>
      <p><%= blog.content %></p>
      <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを作成する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/contacts/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h3>以下の内容で、送信する。</h3>

<%= form_for(@contact) do |f| %>
  <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :content %>

  <!-- @blog.titleと@blog.contentとすることで、表示用の値を画面に出力しています。 -->
  <p>名前:<%= @contact.name %></p>
  <p>アドレス:<%= @contact.email %></p>
  <p>本文:<%= @contact.content %></p>
  <%= f.submit "送信する",class: 'btn btn-primary btn-block'%>
<% end %>

<%= form_for(@contact, url: new_contact_path, method: 'get') do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる" ,name:'back', class: 'btn btn-default btn-block' %>
  <% end %>
  </div>
  </div>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<%= form_for(@contact,url: confirm_contacts_path) do |f| %>
<%= f.error_messages! %>


  <%= f.label :名前 %>
  <%= f.text_field :name,class: 'form-control' %>


  <br>

  <%= f.label :アドレス %>
  <%= f.text_field :email,class: 'form-control'  %>

  <br>

  <%= f.label :内容 %>
  <%= f.text_field :content,class: 'form-control'  %>
  <br>
  <%= f.submit'投稿', class: 'btn btn-primary btn-block' %>


<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abroad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <header>
   <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Abroad", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "お問い合わせ", new_contact_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "ブログ", blogs_path %></li>
          </ul>
        </li>
        
        <li><%= link_to 'マイページ', edit_user_registration_path %></li>
        
        <% if user_signed_in? %>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path  %></li>
              <li><%= link_to 'サインアップ', new_user_registration_path %></li>
        <% end %>



      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  </header>


<%= yield %>

 <footer>
    <p>運営団体 First penguin</p>
    <p>© Copyright First penguin</p>
  </footer>

</body>
</html>

app/views/top/index.html.erb
<p><%= notice %></p>
  <section class="main-header">
     <p class="flash"><%= notice %><%= alert %></p>
    <!-- <img src="<%= asset_path "abroad2.jpeg" %>">  -->
    </section>
   <section class="about">
    <h1>Abroadとは</h1>
    <p>
       Abroadは、海外に挑戦する人のためのアプリです。<br>
    </p>
    <p>
       Abroadを一言で表すと、タスク管理アプリです。<br>
       これから海外に行く人、現地にいる人、海外経験のある人が<br>
       タスクをAcheive上で公開し解決策をシェアすることで<br>
      海外で遭遇する困難を乗り越えて行くことができます。<br>
      今どのようなタスクを行っているかリアルタイムでシェアして行きましょう。
     
    </p>
  </section>
  
  <section class="function container-fluid">
    <h1>Feature</h1>
      <div class="function-images">
           <div class="col-md-3 col-sm-6">  
                <div class="function-image">
                  <img src="<%= asset_path "key.png" %>">
                  <p>ログイン機能</p>
                </div>
            </div>
        
           <div class="col-md-3 col-sm-6">
                <div class="function-image">
                  <img src="<%= asset_path "mails.png" %>">
                  <p>メール送信機能</p>
                </div>
           </div>
        
         <div class="col-md-3 col-sm-6">
            <div class="function-image">
              <img src="<%= asset_path "girls.png" %>">
              <p>友達つながり機能</p>
            </div>
        </div>
        
        <div class="col-md-3 col-sm-6">
            <div class="function-image">
              <img src="<%= asset_path "comment.png" %>">
              <p>コメント投稿機能</p>
            </div>
        </div>
      
      </div>
  </section>
  
  <div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>